behaviors:
  ILWithObstacles:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 0.2
        network_settings:
          hidden_units: 128
          num_layers: 2
        learning_rate: 3.0e-4
        demo_path: Project/Assets/Demonstrations/withObstacleIL.demo
    behavioral_cloning:
      demo_path: Project/Assets/Demonstrations/withObstacleIL.demo
      steps: 50000
      strength: 0.2
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 128
    summary_freq: 20000

