behaviors:
  NavAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      hidden_units: 128
      num_layers: 2
      normalize: false
    max_steps: 300000
    time_horizon: 64
    summary_freq: 5000
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
engine_settings:
  time_scale: 20

